'use client';

import React, { useState } from 'react';
import Navigation from '@/components/Navigation';
import CircuitsDatabaseView from '@/components/database/CircuitsDatabaseView';
import DualDatabaseView from '@/components/database/DualDatabaseView';
import ClusterDatabaseView from '@/components/database/ClusterDatabaseView';
import { Cpu, FileCode, Layers } from 'lucide-react';

type DatabaseTab = 'lmdb' | 'sqlite' | 'cluster';

interface TabInfo {
  id: DatabaseTab;
  label: string;
  icon: React.ReactNode;
  description: string;
}

const tabs: TabInfo[] = [
  {
    id: 'lmdb',
    label: 'LMDB Templates',
    icon: <Cpu size={18} />,
    description: 'SAT-generated identity templates with equivalence classes',
  },
  {
    id: 'sqlite',
    label: 'SQLite Enumerated',
    icon: <FileCode size={18} />,
    description: 'Canonically enumerated circuits',
  },
  {
    id: 'cluster',
    label: 'Cluster SAT',
    icon: <Layers size={18} />,
    description: '46K+ identity circuits from cluster enumeration',
  },
];

export default function DatabasesPage() {
  const [activeTab, setActiveTab] = useState<DatabaseTab>('lmdb');

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 to-slate-900">
      <Navigation />

      <main className="max-w-[1400px] mx-auto p-6">
        <header className="mb-6">
          <h1 className="text-2xl font-bold mb-2 bg-gradient-to-br from-white to-blue-200/90 bg-clip-text text-transparent">
            Circuit Databases
          </h1>
          <p className="text-slate-400">
            Explore circuits from all generation sources
          </p>
        </header>

        <div className="flex gap-2 mb-6 flex-wrap">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all border ${
                activeTab === tab.id
                  ? 'bg-blue-500/20 border-blue-500/50 text-white'
                  : 'bg-slate-800/80 border-slate-600/20 text-slate-400 hover:bg-slate-800 hover:text-white hover:border-slate-500/40'
              }`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.icon}
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        <div className="min-h-[400px]">
          {activeTab === 'lmdb' && (
            <section>
              <div className="mb-4">
                <h2 className="text-lg font-semibold text-white mb-1">
                  SAT Templates (LMDB)
                </h2>
                <p className="text-sm text-slate-400">
                  Optimized identity templates generated by SAT solver
                  enumeration, stored in collection.lmdb with equivalence class
                  grouping.
                </p>
              </div>
              <DualDatabaseView />
            </section>
          )}

          {activeTab === 'sqlite' && (
            <section>
              <div className="mb-4">
                <h2 className="text-lg font-semibold text-white mb-1">
                  Enumerated Circuits (SQLite)
                </h2>
                <p className="text-sm text-slate-400">
                  Circuits generated via the Identity Factory API and stored in
                  circuits.db. Contains canonically enumerated circuits.
                </p>
              </div>
              <CircuitsDatabaseView />
            </section>
          )}

          {activeTab === 'cluster' && (
            <section>
              <div className="mb-4">
                <h2 className="text-lg font-semibold text-white mb-1">
                  Cluster SAT Database
                </h2>
                <p className="text-sm text-slate-400">
                  46K+ identity circuits from cluster SAT enumeration with
                  dimension heatmap, skeleton DAG visualization, and advanced
                  filters.
                </p>
              </div>
              <ClusterDatabaseView />
            </section>
          )}
        </div>
      </main>
    </div>
  );
}
