'use client';

import React, { useState } from 'react';
import Navigation from '@/components/Navigation';
import CircuitsDatabaseView from '@/components/database/CircuitsDatabaseView';
import DualDatabaseView from '@/components/database/DualDatabaseView';
import { Database, Cpu, FileCode } from 'lucide-react';

type DatabaseTab = 'all' | 'main' | 'sat';

interface TabInfo {
  id: DatabaseTab;
  label: string;
  icon: React.ReactNode;
  description: string;
}

const tabs: TabInfo[] = [
  {
    id: 'all',
    label: 'Overview',
    icon: <Database size={18} />,
    description: 'Explore all databases',
  },
  {
    id: 'main',
    label: 'Enumerated (SQLite)',
    icon: <FileCode size={18} />,
    description: 'Canonically enumerated',
  },
  {
    id: 'sat',
    label: 'Templates (LMDB)',
    icon: <Cpu size={18} />,
    description: 'SAT-generated templates',
  },
];

export default function DatabasesPage() {
  const [activeTab, setActiveTab] = useState<DatabaseTab>('all');

  return (
    <div className="page">
      <Navigation />

      <main className="page-content">
        <header className="page-header">
          <h1>Circuit Databases</h1>
          <p>Explore circuits from all generation sources</p>
        </header>

        {/* Database Tabs */}
        <div className="tab-bar">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              className={`tab-btn ${activeTab === tab.id ? 'active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.icon}
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="tab-content">
          {activeTab === 'all' && <DualDatabaseView />}

          {activeTab === 'main' && (
            <section className="database-section">
              <h2>Enumerated Circuits (SQLite)</h2>
              <p className="section-desc">
                Circuits generated via the Identity Factory API and stored in
                circuits.db (SQLite). Contains canonically enumerated circuits.
              </p>
              <CircuitsDatabaseView />
            </section>
          )}

          {activeTab === 'sat' && (
            <section className="database-section">
              <h2>SAT Templates (LMDB)</h2>
              <p className="section-desc">
                Optimized identity templates generated by SAT solver enumeration, 
                stored in collection.lmdb.
              </p>
              <DualDatabaseView />
            </section>
          )}
        </div>
      </main>

      <style jsx>{`
        .page {
          min-height: 100vh;
          background: linear-gradient(180deg, #0a0a0f 0%, #12121a 100%);
        }

        .page-content {
          max-width: 1400px;
          margin: 0 auto;
          padding: 24px;
        }

        .page-header {
          margin-bottom: 24px;
        }

        .page-header h1 {
          font-size: 1.75rem;
          font-weight: 700;
          margin-bottom: 8px;
          background: linear-gradient(135deg, #fff, rgba(150, 200, 255, 0.9));
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .page-header p {
          color: rgba(200, 200, 220, 0.6);
        }

        .tab-bar {
          display: flex;
          gap: 8px;
          margin-bottom: 24px;
          flex-wrap: wrap;
        }

        .tab-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 18px;
          border-radius: 10px;
          background: rgba(30, 30, 45, 0.8);
          border: 1px solid rgba(100, 100, 150, 0.2);
          color: rgba(200, 200, 220, 0.7);
          cursor: pointer;
          font-size: 0.9rem;
          font-weight: 500;
          transition: all 0.2s;
        }

        .tab-btn:hover {
          background: rgba(50, 50, 70, 0.8);
          border-color: rgba(100, 100, 150, 0.4);
          color: #fff;
        }

        .tab-btn.active {
          background: linear-gradient(
            135deg,
            rgba(100, 150, 255, 0.25),
            rgba(80, 100, 200, 0.3)
          );
          border-color: rgba(100, 150, 255, 0.5);
          color: #fff;
        }

        .tab-content {
          min-height: 400px;
        }

        .database-section h2 {
          font-size: 1.2rem;
          font-weight: 600;
          color: #fff;
          margin-bottom: 8px;
        }

        .section-desc {
          color: rgba(200, 200, 220, 0.6);
          font-size: 0.9rem;
          margin-bottom: 20px;
        }
      `}</style>
    </div>
  );
}
